version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/app
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
